### ISSUE TITLE
Error "invalid_scope: Some requested scopes were invalid" when refreshing token

### ISSUE THREAD

**Issue by michaelrod64** [bpasker/nicehashtracker#1]
This can be fixed by changing the scopes constant 

from
`SCOPES = 'https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/gmail.send'`
to
`SCOPES = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/gmail.send']`
on line 26

You also need to add
`creds._scopes = SCOPES` to line 51

Solution from here: https://stackoverflow.com/questions/58942614/google-api-credentials-refresh-failed

**Comment by michaelrod64** [comment]
@bpasker, are you still supporting this at all? I'll submit a pull request if you'll merge it. The script also needs to be updated to use the new nicehash api, which I'll attempt to get working once the 24 hours have passed on my nicehash account allowing me to create an API key

**Comment by michaelrod64** [comment]
If you're using something else besides your script to keep track of mining payouts, please let me know. Open to other suggestions to make managing this easier

**Comment by bpasker** [comment]
Yeah, I have not been using this but I would be happy to merge a PR if to want to submit one.

**Comment by michaelrod64** [comment]
Opened a pull request here: https://github.com/bpasker/nicehashtracker/pull/2

Sorry, I'm new to opening pull requests to other people's repos, so was not sure how to link it to this issue @bpasker

**Comment by bpasker** [comment]
Thank you for the fix! Closing issue with PR merged.
